### ISSUE TITLE
Android 8.0 or Higher version

### ISSUE THREAD

**Issue by ShahidSaud** [jhansireddy/AndroidScannerDemo#89]
Hi Does this Library work with Android 8.0 or higher OS. If not any idea to upgrade the library to support the Android 8.0 or higher versions?

**Comment by massimilianochiodi** [comment]
To me with android 8, compiled with API 28 it works. you just have to check the settings for 'fileprovider' in android.

 I only have problems if I launch from a fragment.

**Comment by zakblacki** [comment]
> To me with android 8, compiled with API 28 it works. you just have to check the settings for 'fileprovider' in android.
> 
> I only have problems if I launch from a fragment.

Please Help I have theses two errors 

error: cannot find symbol variable FileProvider
error: package android.support.v4.content does not exist

**Comment by jhansireddy** [comment]
Have you tried using the package androidx.core.content instead of android.support.v4.content
